name: Run

on:
  workflow_dispatch:

permissions: write-all

env:
  DB_URL: ${{ secrets.DB_URL }}
  CDN_HOST: ${{ secrets.CDN_HOST }}
  SNI_HOST: ${{ secrets.SNI_HOST }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Build LatinaSub-Go
        run: go build -o ./latinasub ./cmd/latinasub/main.go

      - name: Run LatinaSub-Go
        env:
          CONCURRENT: 200
        run: ./latinasub > update.txt

      - uses: actions/upload-artifact@v3
        if: ${{ success() }}
        with:
          name: artifact
          path: update.txt

  Upload-Update:
    needs: [Run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: update.txt

      - name: Delete tag Update if exists
        uses: dev-drprasad/delete-tag-and-release@master
        with:
          delete_release: true
          tag_name: Update
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.11
        with:
          tag_name: Update

      - name: Update Data
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Update
          files: update.txt
          draft: false
          prerelease: true

      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        with:
          id: ${{ steps.release.outputs.id }}
