name: Run

on:
  workflow_dispatch:

env:
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - name: Delete tag Update if exists
        uses: JeelsBoobz/delete-tag-and-release@master
        with:
          delete_release: true
          tag_name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Repo
        uses: richardsimko/update-tag@v1.0.11
        with:
          tag_name: Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build LatinaSub-Go
        run: go build -o ./latinasub ./cmd/latinasub/main.go

      - name: Run LatinaSub-Go
        env:
          CONCURRENT: 200
        run: ./latinasub > update.txt

      - name: Update Data
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Update
          files: update.txt
          prerelease: true
